#!/bin/bash
pacman -S sudo networkmanager vim firefox noto-fonts-cjk noto-fonts-emoji \
xorg xorg-server pipewire wireplumber pipewire-pulse intel-ucode nvtop \
sddm plasma-meta kde-applications plasma-wayland-session packagekit-qt5 \
fcitx5-im fcitx5-chewing fcitx5-qt fcitx5-gtk fcitx5-chinese-addons \
git openssh fakeroot base-devel \
fish less grep nano wget curl \
usbutils
